// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PlayerSettingsHelperPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

enum class Screensaver(val raw: Int) {
  DISABLED(0),
  DVD(1),
  LOGO(2),
  TIME(3),
  BLACK(4);

  companion object {
    fun ofRaw(raw: Int): Screensaver? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VideoPlayerFit(val raw: Int) {
  FILL(0),
  CONTAIN(1),
  COVER(2),
  FIT_WIDTH(3),
  FIT_HEIGHT(4),
  NONE(5),
  SCALE_DOWN(6);

  companion object {
    fun ofRaw(raw: Int): VideoPlayerFit? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlayerOrientations(val raw: Int) {
  PORTRAIT_UP(0),
  PORTRAIT_DOWN(1),
  LAND_SCAPE_LEFT(2),
  LAND_SCAPE_RIGHT(3);

  companion object {
    fun ofRaw(raw: Int): PlayerOrientations? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AutoNextType(val raw: Int) {
  OFF(0),
  STATIC(1),
  SMART(2);

  companion object {
    fun ofRaw(raw: Int): AutoNextType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class SegmentType(val raw: Int) {
  COMMERCIAL(0),
  PREVIEW(1),
  RECAP(2),
  INTRO(3),
  OUTRO(4);

  companion object {
    fun ofRaw(raw: Int): SegmentType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class SegmentSkip(val raw: Int) {
  ASK(0),
  SKIP(1),
  SKIP_ONCE(2),
  NONE(3);

  companion object {
    fun ofRaw(raw: Int): SegmentSkip? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlayerSettings (
  val enableTunneling: Boolean,
  val skipTypes: Map<SegmentType, SegmentSkip>,
  val themeColor: Long? = null,
  val skipForward: Long,
  val skipBackward: Long,
  val autoNextType: AutoNextType,
  val acceptedOrientations: List<PlayerOrientations>,
  val fillScreen: Boolean,
  val videoFit: VideoPlayerFit,
  val screensaver: Screensaver
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlayerSettings {
      val enableTunneling = pigeonVar_list[0] as Boolean
      val skipTypes = pigeonVar_list[1] as Map<SegmentType, SegmentSkip>
      val themeColor = pigeonVar_list[2] as Long?
      val skipForward = pigeonVar_list[3] as Long
      val skipBackward = pigeonVar_list[4] as Long
      val autoNextType = pigeonVar_list[5] as AutoNextType
      val acceptedOrientations = pigeonVar_list[6] as List<PlayerOrientations>
      val fillScreen = pigeonVar_list[7] as Boolean
      val videoFit = pigeonVar_list[8] as VideoPlayerFit
      val screensaver = pigeonVar_list[9] as Screensaver
      return PlayerSettings(enableTunneling, skipTypes, themeColor, skipForward, skipBackward, autoNextType, acceptedOrientations, fillScreen, videoFit, screensaver)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enableTunneling,
      skipTypes,
      themeColor,
      skipForward,
      skipBackward,
      autoNextType,
      acceptedOrientations,
      fillScreen,
      videoFit,
      screensaver,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlayerSettings
    return PlayerSettingsHelperPigeonUtils.deepEquals(this.enableTunneling, other.enableTunneling) && PlayerSettingsHelperPigeonUtils.deepEquals(this.skipTypes, other.skipTypes) && PlayerSettingsHelperPigeonUtils.deepEquals(this.themeColor, other.themeColor) && PlayerSettingsHelperPigeonUtils.deepEquals(this.skipForward, other.skipForward) && PlayerSettingsHelperPigeonUtils.deepEquals(this.skipBackward, other.skipBackward) && PlayerSettingsHelperPigeonUtils.deepEquals(this.autoNextType, other.autoNextType) && PlayerSettingsHelperPigeonUtils.deepEquals(this.acceptedOrientations, other.acceptedOrientations) && PlayerSettingsHelperPigeonUtils.deepEquals(this.fillScreen, other.fillScreen) && PlayerSettingsHelperPigeonUtils.deepEquals(this.videoFit, other.videoFit) && PlayerSettingsHelperPigeonUtils.deepEquals(this.screensaver, other.screensaver)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlayerSettingsHelperPigeonUtils.deepHash(this.enableTunneling)
    result = 31 * result + PlayerSettingsHelperPigeonUtils.deepHash(this.skipTypes)
    result = 31 * result + PlayerSettingsHelperPigeonUtils.deepHash(this.themeColor)
    result = 31 * result + PlayerSettingsHelperPigeonUtils.deepHash(this.skipForward)
    result = 31 * result + PlayerSettingsHelperPigeonUtils.deepHash(this.skipBackward)
    result = 31 * result + PlayerSettingsHelperPigeonUtils.deepHash(this.autoNextType)
    result = 31 * result + PlayerSettingsHelperPigeonUtils.deepHash(this.acceptedOrientations)
    result = 31 * result + PlayerSettingsHelperPigeonUtils.deepHash(this.fillScreen)
    result = 31 * result + PlayerSettingsHelperPigeonUtils.deepHash(this.videoFit)
    result = 31 * result + PlayerSettingsHelperPigeonUtils.deepHash(this.screensaver)
    return result
  }
  override fun toString(): String {
    return "PlayerSettings(enableTunneling=$enableTunneling, skipTypes=$skipTypes, themeColor=$themeColor, skipForward=$skipForward, skipBackward=$skipBackward, autoNextType=$autoNextType, acceptedOrientations=$acceptedOrientations, fillScreen=$fillScreen, videoFit=$videoFit, screensaver=$screensaver)"
  }
}
private open class PlayerSettingsHelperPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Screensaver.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VideoPlayerFit.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlayerOrientations.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AutoNextType.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SegmentType.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SegmentSkip.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlayerSettings.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is Screensaver -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is VideoPlayerFit -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PlayerOrientations -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is AutoNextType -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is SegmentType -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is SegmentSkip -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is PlayerSettings -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PlayerSettingsPigeon {
  fun sendPlayerSettings(playerSettings: PlayerSettings)

  companion object {
    /** The codec used by PlayerSettingsPigeon. */
    val codec: MessageCodec<Any?> by lazy {
      PlayerSettingsHelperPigeonCodec()
    }
    /** Sets up an instance of `PlayerSettingsPigeon` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PlayerSettingsPigeon?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.PlayerSettingsPigeon.sendPlayerSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerSettingsArg = args[0] as PlayerSettings
            val wrapped: List<Any?> = try {
              api.sendPlayerSettings(playerSettingsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlayerSettingsHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
