// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object TranslationsPigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }
}
private open class TranslationsPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class TranslationsPigeon(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TranslationsPigeon. */
    val codec: MessageCodec<Any?> by lazy {
      TranslationsPigeonPigeonCodec()
    }
  }
  suspend fun next(): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.next$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun nextVideo(): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.nextVideo$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun close(): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.close$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun skip(nameArg: String): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.skip$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(nameArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun subtitles(): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.subtitles$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun subtitleSync(): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.subtitleSync$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun off(): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.off$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun chapters(countArg: Long): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.chapters$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(countArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun nextUpInSeconds(secondsArg: Long): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.nextUpInSeconds$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(secondsArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun hoursAndMinutes(timeArg: String): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.hoursAndMinutes$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(timeArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun endsAt(timeArg: String): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.endsAt$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(timeArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun switchChannel(): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.switchChannel$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun switchChannelDesc(programNameArg: String, channelNameArg: String): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.switchChannelDesc$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(programNameArg, channelNameArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun watch(): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.watch$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun now(): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.now$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun decline(): String
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.settings.TranslationsPigeon.decline$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as String
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(TranslationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
