// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object VideoPlayerHelperPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class PlaybackType(val raw: Int) {
  DIRECT(0),
  TRANSCODED(1),
  OFFLINE(2),
  TV(3);

  companion object {
    fun ofRaw(raw: Int): PlaybackType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaSegmentType(val raw: Int) {
  COMMERCIAL(0),
  PREVIEW(1),
  RECAP(2),
  INTRO(3),
  OUTRO(4);

  companion object {
    fun ofRaw(raw: Int): MediaSegmentType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SimpleItemModel (
  val id: String,
  val title: String,
  val subTitle: String? = null,
  val overview: String? = null,
  val logoUrl: String? = null,
  val primaryPoster: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SimpleItemModel {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val subTitle = pigeonVar_list[2] as String?
      val overview = pigeonVar_list[3] as String?
      val logoUrl = pigeonVar_list[4] as String?
      val primaryPoster = pigeonVar_list[5] as String
      return SimpleItemModel(id, title, subTitle, overview, logoUrl, primaryPoster)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      subTitle,
      overview,
      logoUrl,
      primaryPoster,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SimpleItemModel
    return VideoPlayerHelperPigeonUtils.deepEquals(this.id, other.id) && VideoPlayerHelperPigeonUtils.deepEquals(this.title, other.title) && VideoPlayerHelperPigeonUtils.deepEquals(this.subTitle, other.subTitle) && VideoPlayerHelperPigeonUtils.deepEquals(this.overview, other.overview) && VideoPlayerHelperPigeonUtils.deepEquals(this.logoUrl, other.logoUrl) && VideoPlayerHelperPigeonUtils.deepEquals(this.primaryPoster, other.primaryPoster)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.id)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.title)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.subTitle)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.overview)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.logoUrl)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.primaryPoster)
    return result
  }
  override fun toString(): String {
    return "SimpleItemModel(id=$id, title=$title, subTitle=$subTitle, overview=$overview, logoUrl=$logoUrl, primaryPoster=$primaryPoster)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaInfo (
  val playbackType: PlaybackType,
  val videoInformation: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfo {
      val playbackType = pigeonVar_list[0] as PlaybackType
      val videoInformation = pigeonVar_list[1] as String
      return MediaInfo(playbackType, videoInformation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      playbackType,
      videoInformation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaInfo
    return VideoPlayerHelperPigeonUtils.deepEquals(this.playbackType, other.playbackType) && VideoPlayerHelperPigeonUtils.deepEquals(this.videoInformation, other.videoInformation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.playbackType)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.videoInformation)
    return result
  }
  override fun toString(): String {
    return "MediaInfo(playbackType=$playbackType, videoInformation=$videoInformation)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlayableData (
  val currentItem: SimpleItemModel,
  val description: String,
  val startPosition: Long,
  val defaultAudioTrack: Long,
  val audioTracks: List<AudioTrack>,
  val defaultSubtrack: Long,
  val subtitleTracks: List<SubtitleTrack>,
  val trickPlayModel: TrickPlayModel? = null,
  val chapters: List<Chapter>,
  val segments: List<MediaSegment>,
  val previousVideo: SimpleItemModel? = null,
  val nextVideo: SimpleItemModel? = null,
  val mediaInfo: MediaInfo,
  val url: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlayableData {
      val currentItem = pigeonVar_list[0] as SimpleItemModel
      val description = pigeonVar_list[1] as String
      val startPosition = pigeonVar_list[2] as Long
      val defaultAudioTrack = pigeonVar_list[3] as Long
      val audioTracks = pigeonVar_list[4] as List<AudioTrack>
      val defaultSubtrack = pigeonVar_list[5] as Long
      val subtitleTracks = pigeonVar_list[6] as List<SubtitleTrack>
      val trickPlayModel = pigeonVar_list[7] as TrickPlayModel?
      val chapters = pigeonVar_list[8] as List<Chapter>
      val segments = pigeonVar_list[9] as List<MediaSegment>
      val previousVideo = pigeonVar_list[10] as SimpleItemModel?
      val nextVideo = pigeonVar_list[11] as SimpleItemModel?
      val mediaInfo = pigeonVar_list[12] as MediaInfo
      val url = pigeonVar_list[13] as String
      return PlayableData(currentItem, description, startPosition, defaultAudioTrack, audioTracks, defaultSubtrack, subtitleTracks, trickPlayModel, chapters, segments, previousVideo, nextVideo, mediaInfo, url)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      currentItem,
      description,
      startPosition,
      defaultAudioTrack,
      audioTracks,
      defaultSubtrack,
      subtitleTracks,
      trickPlayModel,
      chapters,
      segments,
      previousVideo,
      nextVideo,
      mediaInfo,
      url,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlayableData
    return VideoPlayerHelperPigeonUtils.deepEquals(this.currentItem, other.currentItem) && VideoPlayerHelperPigeonUtils.deepEquals(this.description, other.description) && VideoPlayerHelperPigeonUtils.deepEquals(this.startPosition, other.startPosition) && VideoPlayerHelperPigeonUtils.deepEquals(this.defaultAudioTrack, other.defaultAudioTrack) && VideoPlayerHelperPigeonUtils.deepEquals(this.audioTracks, other.audioTracks) && VideoPlayerHelperPigeonUtils.deepEquals(this.defaultSubtrack, other.defaultSubtrack) && VideoPlayerHelperPigeonUtils.deepEquals(this.subtitleTracks, other.subtitleTracks) && VideoPlayerHelperPigeonUtils.deepEquals(this.trickPlayModel, other.trickPlayModel) && VideoPlayerHelperPigeonUtils.deepEquals(this.chapters, other.chapters) && VideoPlayerHelperPigeonUtils.deepEquals(this.segments, other.segments) && VideoPlayerHelperPigeonUtils.deepEquals(this.previousVideo, other.previousVideo) && VideoPlayerHelperPigeonUtils.deepEquals(this.nextVideo, other.nextVideo) && VideoPlayerHelperPigeonUtils.deepEquals(this.mediaInfo, other.mediaInfo) && VideoPlayerHelperPigeonUtils.deepEquals(this.url, other.url)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.currentItem)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.description)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.startPosition)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.defaultAudioTrack)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.audioTracks)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.defaultSubtrack)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.subtitleTracks)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.trickPlayModel)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.chapters)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.segments)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.previousVideo)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.nextVideo)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.mediaInfo)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.url)
    return result
  }
  override fun toString(): String {
    return "PlayableData(currentItem=$currentItem, description=$description, startPosition=$startPosition, defaultAudioTrack=$defaultAudioTrack, audioTracks=$audioTracks, defaultSubtrack=$defaultSubtrack, subtitleTracks=$subtitleTracks, trickPlayModel=$trickPlayModel, chapters=$chapters, segments=$segments, previousVideo=$previousVideo, nextVideo=$nextVideo, mediaInfo=$mediaInfo, url=$url)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaSegment (
  val type: MediaSegmentType,
  val name: String,
  val start: Long,
  val end: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaSegment {
      val type = pigeonVar_list[0] as MediaSegmentType
      val name = pigeonVar_list[1] as String
      val start = pigeonVar_list[2] as Long
      val end = pigeonVar_list[3] as Long
      return MediaSegment(type, name, start, end)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      name,
      start,
      end,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaSegment
    return VideoPlayerHelperPigeonUtils.deepEquals(this.type, other.type) && VideoPlayerHelperPigeonUtils.deepEquals(this.name, other.name) && VideoPlayerHelperPigeonUtils.deepEquals(this.start, other.start) && VideoPlayerHelperPigeonUtils.deepEquals(this.end, other.end)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.type)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.name)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.start)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.end)
    return result
  }
  override fun toString(): String {
    return "MediaSegment(type=$type, name=$name, start=$start, end=$end)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AudioTrack (
  val name: String,
  val languageCode: String,
  val codec: String,
  val index: Long,
  val external: Boolean,
  val url: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AudioTrack {
      val name = pigeonVar_list[0] as String
      val languageCode = pigeonVar_list[1] as String
      val codec = pigeonVar_list[2] as String
      val index = pigeonVar_list[3] as Long
      val external = pigeonVar_list[4] as Boolean
      val url = pigeonVar_list[5] as String?
      return AudioTrack(name, languageCode, codec, index, external, url)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      languageCode,
      codec,
      index,
      external,
      url,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AudioTrack
    return VideoPlayerHelperPigeonUtils.deepEquals(this.name, other.name) && VideoPlayerHelperPigeonUtils.deepEquals(this.languageCode, other.languageCode) && VideoPlayerHelperPigeonUtils.deepEquals(this.codec, other.codec) && VideoPlayerHelperPigeonUtils.deepEquals(this.index, other.index) && VideoPlayerHelperPigeonUtils.deepEquals(this.external, other.external) && VideoPlayerHelperPigeonUtils.deepEquals(this.url, other.url)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.name)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.languageCode)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.codec)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.index)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.external)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.url)
    return result
  }
  override fun toString(): String {
    return "AudioTrack(name=$name, languageCode=$languageCode, codec=$codec, index=$index, external=$external, url=$url)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SubtitleTrack (
  val name: String,
  val languageCode: String,
  val codec: String,
  val index: Long,
  val external: Boolean,
  val url: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SubtitleTrack {
      val name = pigeonVar_list[0] as String
      val languageCode = pigeonVar_list[1] as String
      val codec = pigeonVar_list[2] as String
      val index = pigeonVar_list[3] as Long
      val external = pigeonVar_list[4] as Boolean
      val url = pigeonVar_list[5] as String?
      return SubtitleTrack(name, languageCode, codec, index, external, url)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      languageCode,
      codec,
      index,
      external,
      url,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SubtitleTrack
    return VideoPlayerHelperPigeonUtils.deepEquals(this.name, other.name) && VideoPlayerHelperPigeonUtils.deepEquals(this.languageCode, other.languageCode) && VideoPlayerHelperPigeonUtils.deepEquals(this.codec, other.codec) && VideoPlayerHelperPigeonUtils.deepEquals(this.index, other.index) && VideoPlayerHelperPigeonUtils.deepEquals(this.external, other.external) && VideoPlayerHelperPigeonUtils.deepEquals(this.url, other.url)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.name)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.languageCode)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.codec)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.index)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.external)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.url)
    return result
  }
  override fun toString(): String {
    return "SubtitleTrack(name=$name, languageCode=$languageCode, codec=$codec, index=$index, external=$external, url=$url)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Chapter (
  val name: String,
  val url: String,
  val time: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Chapter {
      val name = pigeonVar_list[0] as String
      val url = pigeonVar_list[1] as String
      val time = pigeonVar_list[2] as Long
      return Chapter(name, url, time)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      url,
      time,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Chapter
    return VideoPlayerHelperPigeonUtils.deepEquals(this.name, other.name) && VideoPlayerHelperPigeonUtils.deepEquals(this.url, other.url) && VideoPlayerHelperPigeonUtils.deepEquals(this.time, other.time)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.name)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.url)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.time)
    return result
  }
  override fun toString(): String {
    return "Chapter(name=$name, url=$url, time=$time)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TrickPlayModel (
  val width: Long,
  val height: Long,
  val tileWidth: Long,
  val tileHeight: Long,
  val thumbnailCount: Long,
  val interval: Long,
  val images: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrickPlayModel {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      val tileWidth = pigeonVar_list[2] as Long
      val tileHeight = pigeonVar_list[3] as Long
      val thumbnailCount = pigeonVar_list[4] as Long
      val interval = pigeonVar_list[5] as Long
      val images = pigeonVar_list[6] as List<String>
      return TrickPlayModel(width, height, tileWidth, tileHeight, thumbnailCount, interval, images)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
      tileWidth,
      tileHeight,
      thumbnailCount,
      interval,
      images,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TrickPlayModel
    return VideoPlayerHelperPigeonUtils.deepEquals(this.width, other.width) && VideoPlayerHelperPigeonUtils.deepEquals(this.height, other.height) && VideoPlayerHelperPigeonUtils.deepEquals(this.tileWidth, other.tileWidth) && VideoPlayerHelperPigeonUtils.deepEquals(this.tileHeight, other.tileHeight) && VideoPlayerHelperPigeonUtils.deepEquals(this.thumbnailCount, other.thumbnailCount) && VideoPlayerHelperPigeonUtils.deepEquals(this.interval, other.interval) && VideoPlayerHelperPigeonUtils.deepEquals(this.images, other.images)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.width)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.height)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.tileWidth)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.tileHeight)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.thumbnailCount)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.interval)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.images)
    return result
  }
  override fun toString(): String {
    return "TrickPlayModel(width=$width, height=$height, tileWidth=$tileWidth, tileHeight=$tileHeight, thumbnailCount=$thumbnailCount, interval=$interval, images=$images)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StartResult (
  val resultValue: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StartResult {
      val resultValue = pigeonVar_list[0] as String?
      return StartResult(resultValue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      resultValue,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StartResult
    return VideoPlayerHelperPigeonUtils.deepEquals(this.resultValue, other.resultValue)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.resultValue)
    return result
  }
  override fun toString(): String {
    return "StartResult(resultValue=$resultValue)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlaybackState (
  val position: Long,
  val buffered: Long,
  val duration: Long,
  val playing: Boolean,
  val buffering: Boolean,
  val completed: Boolean,
  val failed: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaybackState {
      val position = pigeonVar_list[0] as Long
      val buffered = pigeonVar_list[1] as Long
      val duration = pigeonVar_list[2] as Long
      val playing = pigeonVar_list[3] as Boolean
      val buffering = pigeonVar_list[4] as Boolean
      val completed = pigeonVar_list[5] as Boolean
      val failed = pigeonVar_list[6] as Boolean
      return PlaybackState(position, buffered, duration, playing, buffering, completed, failed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      position,
      buffered,
      duration,
      playing,
      buffering,
      completed,
      failed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlaybackState
    return VideoPlayerHelperPigeonUtils.deepEquals(this.position, other.position) && VideoPlayerHelperPigeonUtils.deepEquals(this.buffered, other.buffered) && VideoPlayerHelperPigeonUtils.deepEquals(this.duration, other.duration) && VideoPlayerHelperPigeonUtils.deepEquals(this.playing, other.playing) && VideoPlayerHelperPigeonUtils.deepEquals(this.buffering, other.buffering) && VideoPlayerHelperPigeonUtils.deepEquals(this.completed, other.completed) && VideoPlayerHelperPigeonUtils.deepEquals(this.failed, other.failed)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.position)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.buffered)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.duration)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.playing)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.buffering)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.completed)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.failed)
    return result
  }
  override fun toString(): String {
    return "PlaybackState(position=$position, buffered=$buffered, duration=$duration, playing=$playing, buffering=$buffering, completed=$completed, failed=$failed)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SubtitleSettings (
  val fontSize: Double,
  val fontWeight: Long,
  val verticalOffset: Double,
  val color: Long,
  val outlineColor: Long,
  val outlineSize: Double,
  val backgroundColor: Long,
  val shadow: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SubtitleSettings {
      val fontSize = pigeonVar_list[0] as Double
      val fontWeight = pigeonVar_list[1] as Long
      val verticalOffset = pigeonVar_list[2] as Double
      val color = pigeonVar_list[3] as Long
      val outlineColor = pigeonVar_list[4] as Long
      val outlineSize = pigeonVar_list[5] as Double
      val backgroundColor = pigeonVar_list[6] as Long
      val shadow = pigeonVar_list[7] as Double
      return SubtitleSettings(fontSize, fontWeight, verticalOffset, color, outlineColor, outlineSize, backgroundColor, shadow)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fontSize,
      fontWeight,
      verticalOffset,
      color,
      outlineColor,
      outlineSize,
      backgroundColor,
      shadow,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SubtitleSettings
    return VideoPlayerHelperPigeonUtils.deepEquals(this.fontSize, other.fontSize) && VideoPlayerHelperPigeonUtils.deepEquals(this.fontWeight, other.fontWeight) && VideoPlayerHelperPigeonUtils.deepEquals(this.verticalOffset, other.verticalOffset) && VideoPlayerHelperPigeonUtils.deepEquals(this.color, other.color) && VideoPlayerHelperPigeonUtils.deepEquals(this.outlineColor, other.outlineColor) && VideoPlayerHelperPigeonUtils.deepEquals(this.outlineSize, other.outlineSize) && VideoPlayerHelperPigeonUtils.deepEquals(this.backgroundColor, other.backgroundColor) && VideoPlayerHelperPigeonUtils.deepEquals(this.shadow, other.shadow)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.fontSize)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.fontWeight)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.verticalOffset)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.color)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.outlineColor)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.outlineSize)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.backgroundColor)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.shadow)
    return result
  }
  override fun toString(): String {
    return "SubtitleSettings(fontSize=$fontSize, fontWeight=$fontWeight, verticalOffset=$verticalOffset, color=$color, outlineColor=$outlineColor, outlineSize=$outlineSize, backgroundColor=$backgroundColor, shadow=$shadow)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TVGuideModel (
  val channels: List<GuideChannel>,
  val startMs: Long,
  val endMs: Long,
  val currentProgram: GuideProgram? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TVGuideModel {
      val channels = pigeonVar_list[0] as List<GuideChannel>
      val startMs = pigeonVar_list[1] as Long
      val endMs = pigeonVar_list[2] as Long
      val currentProgram = pigeonVar_list[3] as GuideProgram?
      return TVGuideModel(channels, startMs, endMs, currentProgram)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      channels,
      startMs,
      endMs,
      currentProgram,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TVGuideModel
    return VideoPlayerHelperPigeonUtils.deepEquals(this.channels, other.channels) && VideoPlayerHelperPigeonUtils.deepEquals(this.startMs, other.startMs) && VideoPlayerHelperPigeonUtils.deepEquals(this.endMs, other.endMs) && VideoPlayerHelperPigeonUtils.deepEquals(this.currentProgram, other.currentProgram)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.channels)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.startMs)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.endMs)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.currentProgram)
    return result
  }
  override fun toString(): String {
    return "TVGuideModel(channels=$channels, startMs=$startMs, endMs=$endMs, currentProgram=$currentProgram)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GuideChannel (
  val channelId: String,
  val name: String,
  val logoUrl: String? = null,
  val programs: List<GuideProgram>,
  val programsLoaded: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GuideChannel {
      val channelId = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val logoUrl = pigeonVar_list[2] as String?
      val programs = pigeonVar_list[3] as List<GuideProgram>
      val programsLoaded = pigeonVar_list[4] as Boolean
      return GuideChannel(channelId, name, logoUrl, programs, programsLoaded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      channelId,
      name,
      logoUrl,
      programs,
      programsLoaded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GuideChannel
    return VideoPlayerHelperPigeonUtils.deepEquals(this.channelId, other.channelId) && VideoPlayerHelperPigeonUtils.deepEquals(this.name, other.name) && VideoPlayerHelperPigeonUtils.deepEquals(this.logoUrl, other.logoUrl) && VideoPlayerHelperPigeonUtils.deepEquals(this.programs, other.programs) && VideoPlayerHelperPigeonUtils.deepEquals(this.programsLoaded, other.programsLoaded)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.channelId)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.name)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.logoUrl)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.programs)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.programsLoaded)
    return result
  }
  override fun toString(): String {
    return "GuideChannel(channelId=$channelId, name=$name, logoUrl=$logoUrl, programs=$programs, programsLoaded=$programsLoaded)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GuideProgram (
  val id: String,
  val channelId: String,
  val name: String,
  val startMs: Long,
  val endMs: Long,
  val primaryPoster: String? = null,
  val overview: String? = null,
  val subTitle: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GuideProgram {
      val id = pigeonVar_list[0] as String
      val channelId = pigeonVar_list[1] as String
      val name = pigeonVar_list[2] as String
      val startMs = pigeonVar_list[3] as Long
      val endMs = pigeonVar_list[4] as Long
      val primaryPoster = pigeonVar_list[5] as String?
      val overview = pigeonVar_list[6] as String?
      val subTitle = pigeonVar_list[7] as String?
      return GuideProgram(id, channelId, name, startMs, endMs, primaryPoster, overview, subTitle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      channelId,
      name,
      startMs,
      endMs,
      primaryPoster,
      overview,
      subTitle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GuideProgram
    return VideoPlayerHelperPigeonUtils.deepEquals(this.id, other.id) && VideoPlayerHelperPigeonUtils.deepEquals(this.channelId, other.channelId) && VideoPlayerHelperPigeonUtils.deepEquals(this.name, other.name) && VideoPlayerHelperPigeonUtils.deepEquals(this.startMs, other.startMs) && VideoPlayerHelperPigeonUtils.deepEquals(this.endMs, other.endMs) && VideoPlayerHelperPigeonUtils.deepEquals(this.primaryPoster, other.primaryPoster) && VideoPlayerHelperPigeonUtils.deepEquals(this.overview, other.overview) && VideoPlayerHelperPigeonUtils.deepEquals(this.subTitle, other.subTitle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.id)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.channelId)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.name)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.startMs)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.endMs)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.primaryPoster)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.overview)
    result = 31 * result + VideoPlayerHelperPigeonUtils.deepHash(this.subTitle)
    return result
  }
  override fun toString(): String {
    return "GuideProgram(id=$id, channelId=$channelId, name=$name, startMs=$startMs, endMs=$endMs, primaryPoster=$primaryPoster, overview=$overview, subTitle=$subTitle)"
  }
}
private open class VideoPlayerHelperPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlaybackType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaSegmentType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SimpleItemModel.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfo.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlayableData.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaSegment.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AudioTrack.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SubtitleTrack.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Chapter.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrickPlayModel.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StartResult.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaybackState.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SubtitleSettings.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TVGuideModel.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GuideChannel.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GuideProgram.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlaybackType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is MediaSegmentType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is SimpleItemModel -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is MediaInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PlayableData -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MediaSegment -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is AudioTrack -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is SubtitleTrack -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is Chapter -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is TrickPlayModel -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is StartResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is PlaybackState -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is SubtitleSettings -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is TVGuideModel -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is GuideChannel -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is GuideProgram -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeVideoActivity {
  suspend fun launchActivity(): StartResult
  fun disposeActivity()
  fun isLeanBackEnabled(): Boolean

  companion object {
    /** The codec used by NativeVideoActivity. */
    val codec: MessageCodec<Any?> by lazy {
      VideoPlayerHelperPigeonCodec()
    }
    /** Sets up an instance of `NativeVideoActivity` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeVideoActivity?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.NativeVideoActivity.launchActivity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.launchActivity())
              } catch (exception: Throwable) {
                VideoPlayerHelperPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.NativeVideoActivity.disposeActivity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disposeActivity()
              listOf(null)
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.NativeVideoActivity.isLeanBackEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isLeanBackEnabled())
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VideoPlayerApi {
  suspend fun sendPlayableModel(playableData: PlayableData): Boolean
  suspend fun sendTVGuideModel(guide: TVGuideModel): Boolean
  suspend fun open(url: String, play: Boolean): Boolean
  fun setLooping(looping: Boolean)
  /** Sets the volume, with 0.0 being muted and 1.0 being full volume. */
  fun setVolume(volume: Double)
  /** Sets the playback speed as a multiple of normal speed. */
  fun setPlaybackSpeed(speed: Double)
  fun play()
  /** Pauses playback if the video is currently playing. */
  fun pause()
  /** Seeks to the given playback position, in milliseconds. */
  fun seekTo(position: Long)
  fun stop()
  fun setSubtitleSettings(settings: SubtitleSettings)
  /**
   * Shifts subtitle timing by the given offset, in milliseconds. Positive
   * values delay the subtitles (show them later), negative shows them earlier.
   */
  fun setSubtitleDelay(delayMs: Long)

  companion object {
    /** The codec used by VideoPlayerApi. */
    val codec: MessageCodec<Any?> by lazy {
      VideoPlayerHelperPigeonCodec()
    }
    /** Sets up an instance of `VideoPlayerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VideoPlayerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.sendPlayableModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playableDataArg = args[0] as PlayableData
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.sendPlayableModel(playableDataArg))
              } catch (exception: Throwable) {
                VideoPlayerHelperPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.sendTVGuideModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val guideArg = args[0] as TVGuideModel
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.sendTVGuideModel(guideArg))
              } catch (exception: Throwable) {
                VideoPlayerHelperPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val playArg = args[1] as Boolean
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.open(urlArg, playArg))
              } catch (exception: Throwable) {
                VideoPlayerHelperPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.setLooping$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val loopingArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setLooping(loopingArg)
              listOf(null)
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.setVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val volumeArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setVolume(volumeArg)
              listOf(null)
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.setPlaybackSpeed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val speedArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setPlaybackSpeed(speedArg)
              listOf(null)
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.play()
              listOf(null)
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pause()
              listOf(null)
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.seekTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val positionArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.seekTo(positionArg)
              listOf(null)
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.setSubtitleSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as SubtitleSettings
            val wrapped: List<Any?> = try {
              api.setSubtitleSettings(settingsArg)
              listOf(null)
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerApi.setSubtitleDelay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val delayMsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setSubtitleDelay(delayMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              VideoPlayerHelperPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VideoPlayerListenerCallback(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VideoPlayerListenerCallback. */
    val codec: MessageCodec<Any?> by lazy {
      VideoPlayerHelperPigeonCodec()
    }
  }
  suspend fun onPlaybackStateChanged(stateArg: PlaybackState)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerListenerCallback.onPlaybackStateChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(stateArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(VideoPlayerHelperPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VideoPlayerControlsCallback(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VideoPlayerControlsCallback. */
    val codec: MessageCodec<Any?> by lazy {
      VideoPlayerHelperPigeonCodec()
    }
  }
  suspend fun loadNextVideo()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerControlsCallback.loadNextVideo$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(VideoPlayerHelperPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun loadPreviousVideo()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerControlsCallback.loadPreviousVideo$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(VideoPlayerHelperPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onStop()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerControlsCallback.onStop$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(VideoPlayerHelperPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun swapSubtitleTrack(valueArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerControlsCallback.swapSubtitleTrack$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(valueArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(VideoPlayerHelperPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun swapAudioTrack(valueArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerControlsCallback.swapAudioTrack$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(valueArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(VideoPlayerHelperPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun loadProgram(selectionArg: GuideChannel)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerControlsCallback.loadProgram$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(selectionArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(VideoPlayerHelperPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun fetchProgramsForChannel(channelIdArg: String): List<GuideProgram>
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.io_github_hamadtheironside_driftfin.video.VideoPlayerControlsCallback.fetchProgramsForChannel$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(channelIdArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as List<GuideProgram>
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(VideoPlayerHelperPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
